### ISSUE TITLE
Issues on import BrightkyEmitter

### ISSUE THREAD

**Issue by papsrowan** [BrightkyEfoo/event-emitter#2]
when I try to import BrightkyEmitter in my code it Fails.
```
const BrightkyEmitter = require("brightkyefoo-event-emitter");

const emitter = new BrightkyEmitter();

emitter.on("yo", () => {
  console.log("yooo");
});

emitter.emit("yo", undefined);
```
That's my code.
What should i do ?

**Comment by BrightkyEfoo** [comment]
What message do you get in your terminal when you run

**Comment by papsrowan** [comment]
I get this error
![image](https://github.com/BrightkyEfoo/event-emitter/assets/92266315/7df13aca-9383-4626-bded-0cf425921b2e)

**Comment by BrightkyEfoo** [comment]
Oohh! Try to change the require to import statement like this
```
import BrightkyEmitter from "brightkyefoo-event-emitter";
```
And then add `"type":"module"` to your `package.json`
like this :
![image](https://github.com/BrightkyEfoo/event-emitter/assets/108243838/4654f438-d57b-4fa7-be69-ff8cdad00dcd)

**Comment by papsrowan** [comment]
Great It works. Thks

**Comment by papsrowan** [comment]
thks
